<?php
/**
 * Actions Framework.
 *
 * WARNING: This file is part of the core Actions Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Actions
 * @author  WPDevHQ
 * @license GPL-2.0+
 * @link    http://www.wpdevhq.com/themes/actions/
 */
 
function actions() {

get_header();
 
    do_action( 'actions_before_content_wrapper' );
	
	do_action( 'actions_before_index' );
	
        if ( have_posts() ) :
		
		    do_action( 'actions_before_index_elements' );
			
			    do_action( 'actions_index_elements' );
				
			do_action( 'actions_after_index_elements' );
        
		// If no content, include the "No posts found" template.
		else :
			do_action( 'actions_before_content_none' );
			
			    do_action( 'actions_index_content_none' );
				
			do_action( 'actions_after_content_none' );
			
		endif;
		
    do_action( 'actions_after_content_wrapper' );
	
	do_action( 'actions_sidebar' );
	
get_footer();
}